### ISSUE TITLE
How to handle echart `callback` functions within the echarm?

### ISSUE THREAD

**Issue by ramkumarkb** [lublak/typst-echarm-package#2]
Hi,

I am trying to render pie-chart with labels - 
https://echarts.apache.org/examples/en/editor.html?c=pie-alignTo OR 
https://echarts.apache.org/examples/en/editor.html?c=pie-labelLine-adjust 

It looks like `echarm` does not seem to work when `label` attribute is turned on `"show": true` 

Any tips or guidance would be very helpful. Thank you 🙏 

### Does not work:

```
#set page(width: 200mm, height: 150mm, margin: 5mm)
#import "@preview/echarm:0.1.0"

#let pie_data = (
  ////////////////////////////////////////
  (
    ( name: "圣彼得堡来客", value: 5.6 ),
    ( name: "陀思妥耶夫斯基全集", value: 1 ),
    ( name: "史记精注全译 (全6册) ", value: 0.8 ),
    ( name: "加德纳艺术通史", value: 0.5 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  ),
  // ////////////////////////////////////////
  (
    ( name: "银河帝国5: 迈向基地", value: 3.8 ),
    ( name: "俞军产品方法论", value: 2.3 ),
    ( name: "艺术的逃难", value: 2.2 ),
    ( name: "第一次世界大战回忆录（全五卷）", value: 1.3 ),
    ( name: "Scrum 精髓", value: 1.2 ),
    ( name: "其它", value: 5.7 )
  ),
  ////////////////////////////////////////
  (
    ( name: "克莱因壶", value: 3.5 ),
    ( name: "投资最重要的事", value: 2.8 ),
    ( name: "简读中国史", value: 1.7 ),
    ( name: "你当像鸟飞往你的山", value: 1.4 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  )
)

#echarm.render(width: 100%, height: 100%, options: (
  textStyle: (
    fontFamily:"Tahoma"
   ),

  title: (
    text: "阅读书籍分布",
    left: "center",
    textStyle: (
      color: "#999",
      fontWeight: "normal",
      fontSize: 14
    )
  ),

  series: ( 
      name: "eCharm Pie",
      type: "pie",
      radius: ("20%", "60%"),
      top: "10%",
      height: "50.00%",
      left: "center",
      width: 400,
      itemStyle: (
        borderColor: "#fff",
        borderWidth: 1
      ),

      label: (
        "show": true,
        position: "outer",
        alignTo: "none",
        bleedMargin: 5
        // formatter: "(name|(b))\n(time|(c) 小时)",
        // minMargin: 5,
        // edgeDistance: 10,
        // lineHeight: 15,
        // rich: (
        //   time: (
        //     fontSize: 10,
        //     color: "#999"
        //   ),
        // ),
      ),

      // labelLine: (
      //   "show": true
      //   length: 15,
      //   length2: 0,
      //   maxSurfaceAngle: 80
      // ),

      // labelLayout: "",

      data: pie_data.at(0)

    )
)
)

```

### Works:

```
#set page(width: 200mm, height: 150mm, margin: 5mm)
#import "@preview/echarm:0.1.0"

#let pie_data = (
  ////////////////////////////////////////
  (
    ( name: "圣彼得堡来客", value: 5.6 ),
    ( name: "陀思妥耶夫斯基全集", value: 1 ),
    ( name: "史记精注全译 (全6册) ", value: 0.8 ),
    ( name: "加德纳艺术通史", value: 0.5 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  ),
  // ////////////////////////////////////////
  (
    ( name: "银河帝国5: 迈向基地", value: 3.8 ),
    ( name: "俞军产品方法论", value: 2.3 ),
    ( name: "艺术的逃难", value: 2.2 ),
    ( name: "第一次世界大战回忆录（全五卷）", value: 1.3 ),
    ( name: "Scrum 精髓", value: 1.2 ),
    ( name: "其它", value: 5.7 )
  ),
  ////////////////////////////////////////
  (
    ( name: "克莱因壶", value: 3.5 ),
    ( name: "投资最重要的事", value: 2.8 ),
    ( name: "简读中国史", value: 1.7 ),
    ( name: "你当像鸟飞往你的山", value: 1.4 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  )
)

#echarm.render(width: 100%, height: 100%, options: (
  textStyle: (
    fontFamily:"Tahoma"
   ),

  title: (
    text: "阅读书籍分布",
    left: "center",
    textStyle: (
      color: "#999",
      fontWeight: "normal",
      fontSize: 14
    )
  ),

  series: ( 
      name: "eCharm Pie",
      type: "pie",
      radius: ("20%", "60%"),
      top: "10%",
      height: "50.00%",
      left: "center",
      width: 400,
      itemStyle: (
        borderColor: "#fff",
        borderWidth: 1
      ),

      label: (
        "show": false,
        position: "outer",
        alignTo: "none",
        bleedMargin: 5
        // formatter: "(name|(b))\n(time|(c) 小时)",
        // minMargin: 5,
        // edgeDistance: 10,
        // lineHeight: 15,
        // rich: (
        //   time: (
        //     fontSize: 10,
        //     color: "#999"
        //   ),
        // ),
      ),

      // labelLine: (
      //   "show": true
      //   length: 15,
      //   length2: 0,
      //   maxSurfaceAngle: 80
      // ),

      // labelLayout: "",

      data: pie_data.at(0)

    )
)
)
```

**Comment by lublak** [comment]
@ramkumarkb i tested it myself, for me it works fine. Do you use tinymist or do you use typst c test.typ?

![image](https://github.com/user-attachments/assets/7f9e24e6-5f68-4606-ac13-2ff7e2f07559)
[test.pdf](https://github.com/user-attachments/files/17780236/test.pdf)

**Comment by ramkumarkb** [comment]
@lublak  - Thank you for the feedback. My apologies that the issue was not explained clearly - after some investigation the issue is not with the `label` per se but on how to handle the callback functions that are used in the echarts. See the example below.  I have thus changed the issue title to better reflect the actual issue - 

Example - https://echarts.apache.org/examples/en/editor.html?c=pie-labelLine-adjust 

```
      labelLayout: function (params) {
        const isLeft = params.labelRect.x < myChart.getWidth() / 2;
        const points = params.labelLinePoints;
        // Update the end point.
        points[2][0] = isLeft
          ? params.labelRect.x
          : params.labelRect.x + params.labelRect.width;
        return {
          labelLinePoints: points
        };
      },
      ```

**Comment by ramkumarkb** [comment]
Hi,

I tried out a few things - now am able to compile w/o any errors and the pie-chart generates - but I am not sure if the function is really working - AFAIK - in typst `points[2][0]` is not a valid syntax... ?

Again, any guidance would be super helpful... 🙏 

```
      labelLayout: (params) => {
        let isLeft = params.labelRect.x < myChart.getWidth() / 2
        let points = params.labelLinePoints // as number[][]

        // Update the end point.
        // points[2][0] = isLeft
        //   ? params.labelRect.x
        //   : params.labelRect.x + params.labelRect.width

        points[2][0] = if isLeft {
          params.labelRect.x 
        } else {
          params.labelRect.x + params.labelRect.width  
        }

        (
          labelLinePoints: points
        )
      },


```

**Comment by ramkumarkb** [comment]
I tried this but did not work either.  `points.at(2).at(0)` would the 2D equivalent in Typst. 

Can eCharm work with callbacks or it will only with `(name:value)` attributes ?

```
      labelLayout: (params) => {
        let isLeft = params.labelRect.x < myChart.getWidth() / 2
        let points = params.labelLinePoints // as number[][]

        // Update the end point.
        // points[2][0] = isLeft
        //   ? params.labelRect.x
        //   : params.labelRect.x + params.labelRect.width

        points.at(2).at(0) = if isLeft {
          params.labelRect.x 
        } else {
          params.labelRect.x + params.labelRect.width  
        }

        (
          labelLinePoints: points
        )
      },
```

**Comment by lublak** [comment]
@ramkumarkb currently there is no way to pass a typst function as a callback to JavaScript. Hmmm I need to think about this. I think it's a limitation of the typst plugin system. I will look at it.
As a workaround, a string which is a JavaScript function which is parsed on the fly. But this is currently not supported on Ctxjs yet (but this should be possible?).

**Comment by ramkumarkb** [comment]
@lublak - Thank you for the reply and the confirmation 🙏 
I am always at awe for Ctxjs 🎉  and value it brings to the Typst ecosystem 💯

**Comment by lublak** [comment]
@ramkumarkb I currently have an idea about a “magic” string.
On your example it would look like

```typ
labelLayout: "eval:(params) => ...",
```

so you could define objects in typst and still attach a javascript object.

**Comment by lublak** [comment]
@ramkumarkb yes. It would be a entire Javascript Funtion with JS syntax. eval: just says my rust code: hey this should be interpreted.

1. for this i need to work on Ctxjs (new function: call_module_function_with_eval(), build and publish
2. Update echarm to the new released version
3. Use the new rust function (in a new echarm render function)
```typ
#{
ctxjs.call-module-function-with-eval(
  "@preview/echarm",
  "echarts_helper",
  "render",
  (
    calc_width / zoom,
    calc_height / zoom,
    options,
  ),
  "eval" // its the tag "eval: ...", option to change it! If someone needs to use "eval: " as a label
)
}
```
4. build everything publish

Currently an alternative approuch:

1. collect all functions of a typst object
2. store them in to a value
5. create a fake function that collects the parameters 
6. return all parameters and execute the typst functions
7. get the result of the type functions and rerender the echarm object

But this is more complex and requires to render two? multiple? times. Also it could backfire with some other issues.
Sadly there is no option to communicate with typst directly.

**Comment by ramkumarkb** [comment]
@lublak - the 1st approach looks straightforward to reason about - at least as a user, though I am not sure the complexity of implementing the `call-module-function-with-eval` in Rust. 

Typst authors mentioned that they will upgrading the WASM engine to a faster version in the very near future. So may be this approach makes even more sense... ?

Again, thanks for taking time to explain the details of the solution 🥇

**Comment by ramkumarkb** [comment]
@lublak  - I was going thru the `ctxjs` code - so if I understand the idea - it would be to add a new function:
 `call-module-function-with-eval`  in the file - https://github.com/lublak/typst-ctxjs-package/blob/main/src/lib.rs

**Comment by lublak** [comment]
@ramkumarkb I think modifying the `call-module-function` is also fine.
eval_tag = "" could be the default (disabled)

**Comment by ramkumarkb** [comment]
@lublak - ok, noted. I am new to rust and the wasm toolchain. So it will probably take me lot longer to give you a PR. If you plan to do this, I can support you on testing 😳

**Comment by lublak** [comment]
@ramkumarkb i will work on it, but not this week. Maybe weekend.

**Comment by ramkumarkb** [comment]
@lublak - I know that this is super awkward (at least for me) to chase an open-source contributor for a patch - but were you able to take a look at this feature? 🙏

**Comment by lublak** [comment]
@ramkumarkb I can't promise you anything. Unfortunately, Windows completely destroyed itself on my system, including a partition table on my connected hard drive.
That's why I'm in the process of switching to Linux. Including rebuilding my development environment.
It's a lot of work, as I'm also setting up a backup solution at the same time.

**Comment by lublak** [comment]
@ramkumarkb I have been able to work again since yesterday.
So I can now look at it over the next few days.

**Comment by ramkumarkb** [comment]
@lublak - I can only thank you for the help and now will wait with bated breath for any update 🙏 🥇

**Comment by lublak** [comment]
Just some information also as a note:
new approuch would be like this:

```
labelLayout: eval-later("(params) => {
        const isLeft = params.labelRect.x < myChart.getWidth() / 2;
        const points = params.labelLinePoints;
        // Update the end point.
        points[2][0] = isLeft
          ? params.labelRect.x
          : params.labelRect.x + params.labelRect.width;
        return {
          labelLinePoints: points
        };
}", type-field: "$type"), // $type ist default?
```

eval_later is a typst function which just wraps the string into an object (only as an example, could look different for the final release):

```
(
  "$type": "eval",
  value: "(params) => {........"
)
```

in echarm:

```
#{
ctxjs.call-module-function-with-eval(
  "@preview/echarm",
  "echarts_helper",
  "render",
  (
    calc_width / zoom,
    calc_height / zoom,
    options,
  ),
  type-field: "$type" // the same from eval-later
)
}
```

at some point, this could lead to the possibility of offering even more (compile eval-later to bytecode):


```
(
  "$type": "eval_bytecode",
  value: "bytecode"
)
```

**Comment by lublak** [comment]
@ramkumarkb

ctx now supports a untested eval-later, if everything goes right: i can test it tomorrow completely and  publish it to universe. After it gets approved, i update echarm to the latest ctx version and publish it directly. It should than directly support call-later without any changes on the echarm side (just a shortcut for eval-later would be helpful, i think)

```
ctxjs.eval-later
```

**Comment by lublak** [comment]
@ramkumarkb 

should do the trick (warning: you don't have access to "mychart"!)

```typ
#set page(width: 200mm, height: 150mm, margin: 5mm)
#import "lib.typ" as echarm

#let pie_data = (
  ////////////////////////////////////////
  (
    ( name: "圣彼得堡来客", value: 5.6 ),
    ( name: "陀思妥耶夫斯基全集", value: 1 ),
    ( name: "史记精注全译 (全6册) ", value: 0.8 ),
    ( name: "加德纳艺术通史", value: 0.5 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  ),
  // ////////////////////////////////////////
  (
    ( name: "银河帝国5: 迈向基地", value: 3.8 ),
    ( name: "俞军产品方法论", value: 2.3 ),
    ( name: "艺术的逃难", value: 2.2 ),
    ( name: "第一次世界大战回忆录（全五卷）", value: 1.3 ),
    ( name: "Scrum 精髓", value: 1.2 ),
    ( name: "其它", value: 5.7 )
  ),
  ////////////////////////////////////////
  (
    ( name: "克莱因壶", value: 3.5 ),
    ( name: "投资最重要的事", value: 2.8 ),
    ( name: "简读中国史", value: 1.7 ),
    ( name: "你当像鸟飞往你的山", value: 1.4 ),
    ( name: "表象与本质", value: 0.5 ),
    ( name: "其它", value: 3.8 )
  )
)

#echarm.render(width: 100%, height: 100%, options: (
  textStyle: (
    fontFamily:"Tahoma"
   ),

  title: (
    text: "阅读书籍分布",
    left: "center",
    textStyle: (
      color: "#999",
      fontWeight: "normal",
      fontSize: 14
    )
  ),

  series: ( 
      name: "eCharm Pie",
      type: "pie",
      radius: ("20%", "60%"),
      top: "10%",
      height: "50.00%",
      left: "center",
      width: 400,
      itemStyle: (
        borderColor: "#fff",
        borderWidth: 1
      ),

      label: (
        "show": true,
        position: "outer",
        alignTo: "none",
        bleedMargin: 5,
        formatter: "(name|(b))\n(time|(c) 小时)",
        minMargin: 5,
        edgeDistance: 10,
        lineHeight: 15,
        rich: (
          time: (
            fontSize: 10,
            color: "#999"
          ),
        ),
      ),

      labelLine: (
        "show": true,
        length: 15,
        length2: 0,
        maxSurfaceAngle: 80
      ),

      labelLayout: echarm.eval-later("(params) => {
        const isLeft = params.labelRect.x < " + str((200mm).pt()) + " / 2;
        const points = params.labelLinePoints;
        // Update the end point.
        points[2][0] = isLeft
          ? params.labelRect.x
          : params.labelRect.x + params.labelRect.width;
        return {
          labelLinePoints: points
        };
      }"),

      data: pie_data.at(0)

    )
)
)
```

![grafik](https://github.com/user-attachments/assets/3b7b8cf5-851a-4238-9397-5eb911236e24)

**Comment by ramkumarkb** [comment]
I cannot thank you enuf for this enhancement 🎉💥
Now I have to wait with bated breath for the echarms v0.1.1 to be published 🥳
